version: '3.3'
services:
  manager:
    build: manager
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - PORT=8080
      - WORKER_HOST=worker
      - WORKER_PORT=8081

  worker:
    build: worker
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - PORT=8081
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080